/* =====================================================================
   NGX POS & ERP — SQL Server schema mirror
   Phase 1: Authentication & Security
   =====================================================================
   Mirrors: prisma/schema.prisma (models User, Role, Permission,
            RolePermission, UserRole, Session) as of the Phase 1 commit.

   This is a MANUALLY MAINTAINED mirror for portability/reference only.
   The live application runs on PostgreSQL via Prisma — see
   db-scripts/README.md for what this file is and is not.

   Tested against: NOT YET RUN against a real SQL Server instance.
   Verify before relying on this in a real deployment.

   Notes on translation choices from the Prisma/Postgres schema:
   - Prisma's cuid() primary keys are opaque strings generated by the
     application, not the database — so these are NVARCHAR primary keys,
     not IDENTITY/UNIQUEIDENTIFIER columns. The application must still
     generate the id before insert when using this schema directly.
   - Prisma's DateTime -> DATETIME2 (UTC, application-managed).
   - Prisma's @updatedAt is application-managed here too (no trigger);
     if you insert/update rows directly via SQL outside the app, remember
     to set updatedAt yourself.
   - Session.tokenHash stores a SHA-256 hex digest (64 characters).
   ===================================================================== */

SET NOCOUNT ON;
GO

/* ---------------------------------------------------------------------
   Users
   --------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Users')
BEGIN
    CREATE TABLE dbo.Users (
        Id                  NVARCHAR(50)   NOT NULL PRIMARY KEY,
        Username            NVARCHAR(100)  NOT NULL,
        Email               NVARCHAR(255)  NOT NULL,
        PasswordHash        NVARCHAR(255)  NOT NULL,
        FullName            NVARCHAR(200)  NOT NULL,
        IsActive            BIT            NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
        FailedLoginAttempts INT            NOT NULL CONSTRAINT DF_Users_FailedLoginAttempts DEFAULT (0),
        LockedUntil         DATETIME2      NULL,
        LastLoginAt         DATETIME2      NULL,
        CreatedAt           DATETIME2      NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CreatedBy           NVARCHAR(50)   NULL,
        UpdatedAt           DATETIME2      NOT NULL CONSTRAINT DF_Users_UpdatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedBy           NVARCHAR(50)   NULL,
        DeletedAt           DATETIME2      NULL,
        CONSTRAINT UQ_Users_Username UNIQUE (Username),
        CONSTRAINT UQ_Users_Email UNIQUE (Email)
    );

    CREATE INDEX IX_Users_Email ON dbo.Users (Email);
    CREATE INDEX IX_Users_Username ON dbo.Users (Username);
END
GO

/* ---------------------------------------------------------------------
   Roles
   --------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Roles')
BEGIN
    CREATE TABLE dbo.Roles (
        Id           NVARCHAR(50)  NOT NULL PRIMARY KEY,
        Code         NVARCHAR(50)  NOT NULL,
        Name         NVARCHAR(150) NOT NULL,
        Description  NVARCHAR(500) NULL,
        -- A super-admin role bypasses granular permission checks in the
        -- application layer. See docs/DECISIONS.md for why this exists.
        IsSuperAdmin BIT           NOT NULL CONSTRAINT DF_Roles_IsSuperAdmin DEFAULT (0),
        CreatedAt    DATETIME2     NOT NULL CONSTRAINT DF_Roles_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt    DATETIME2     NOT NULL CONSTRAINT DF_Roles_UpdatedAt DEFAULT (SYSUTCDATETIME()),
        DeletedAt    DATETIME2     NULL,
        CONSTRAINT UQ_Roles_Code UNIQUE (Code)
    );
END
GO

/* ---------------------------------------------------------------------
   Permissions
   --------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Permissions')
BEGIN
    CREATE TABLE dbo.Permissions (
        Id          NVARCHAR(50)  NOT NULL PRIMARY KEY,
        Code        NVARCHAR(150) NOT NULL, -- e.g. 'sales.invoice.create'
        Module      NVARCHAR(100) NOT NULL, -- e.g. 'sales'
        Action      NVARCHAR(100) NOT NULL, -- e.g. 'create'
        Description NVARCHAR(500) NULL,
        CreatedAt   DATETIME2     NOT NULL CONSTRAINT DF_Permissions_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT UQ_Permissions_Code UNIQUE (Code)
    );

    CREATE INDEX IX_Permissions_Module ON dbo.Permissions (Module);
END
GO

/* ---------------------------------------------------------------------
   RolePermissions (join table)
   --------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RolePermissions')
BEGIN
    CREATE TABLE dbo.RolePermissions (
        Id           NVARCHAR(50) NOT NULL PRIMARY KEY,
        RoleId       NVARCHAR(50) NOT NULL,
        PermissionId NVARCHAR(50) NOT NULL,
        CreatedAt    DATETIME2    NOT NULL CONSTRAINT DF_RolePermissions_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT UQ_RolePermissions_Role_Permission UNIQUE (RoleId, PermissionId),
        CONSTRAINT FK_RolePermissions_Role
            FOREIGN KEY (RoleId) REFERENCES dbo.Roles (Id) ON DELETE CASCADE,
        CONSTRAINT FK_RolePermissions_Permission
            FOREIGN KEY (PermissionId) REFERENCES dbo.Permissions (Id) ON DELETE CASCADE
    );
END
GO

/* ---------------------------------------------------------------------
   UserRoles (join table)
   --------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'UserRoles')
BEGIN
    CREATE TABLE dbo.UserRoles (
        Id        NVARCHAR(50) NOT NULL PRIMARY KEY,
        UserId    NVARCHAR(50) NOT NULL,
        RoleId    NVARCHAR(50) NOT NULL,
        CreatedAt DATETIME2    NOT NULL CONSTRAINT DF_UserRoles_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT UQ_UserRoles_User_Role UNIQUE (UserId, RoleId),
        CONSTRAINT FK_UserRoles_User
            FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE,
        CONSTRAINT FK_UserRoles_Role
            FOREIGN KEY (RoleId) REFERENCES dbo.Roles (Id) ON DELETE CASCADE
    );
END
GO

/* ---------------------------------------------------------------------
   Sessions
   --------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Sessions')
BEGIN
    CREATE TABLE dbo.Sessions (
        Id        NVARCHAR(50)  NOT NULL PRIMARY KEY,
        UserId    NVARCHAR(50)  NOT NULL,
        -- SHA-256 hex digest of the opaque session token. The raw token
        -- itself lives only in the browser's cookie, never in this table.
        TokenHash CHAR(64)      NOT NULL,
        IpAddress NVARCHAR(45)  NULL,
        UserAgent NVARCHAR(500) NULL,
        ExpiresAt DATETIME2     NOT NULL,
        RevokedAt DATETIME2     NULL,
        CreatedAt DATETIME2     NOT NULL CONSTRAINT DF_Sessions_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT UQ_Sessions_TokenHash UNIQUE (TokenHash),
        CONSTRAINT FK_Sessions_User
            FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE
    );

    CREATE INDEX IX_Sessions_UserId ON dbo.Sessions (UserId);
END
GO
